# Generated by Django 5.2.6 on 2025-09-17 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('responsavel_nome', models.CharField(max_length=100)),
                ('responsavel_contato', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(default='Fase de Grupos', max_length=50)),
                ('gols_time_casa', models.IntegerField(default=0)),
                ('gols_time_visitante', models.IntegerField(default=0)),
                ('data_partida', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
                ('partida_realizada', models.BooleanField(default=False)),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_casa', to='campeonato.time')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='campeonato.time')),
            ],
        ),
    ]
